### ISSUE TITLE
Should we handle negative integer or just the positive one?

### ISSUE THREAD

**Issue by LiawiFelix** [compiler-f20/discussion#17]
-123 can be considered as minus 123, but the testcase treat - as "-" and "123" as integer.  So, does it means that we only need to considered the positive integer value? You can reply in Chinese, Thank you very much

**Comment by chrisPyr** [comment]
@LiawiFelix 
You don't need to handle the negative integer.In spec, it's said 
"Integer Constants:
A sequence of one or more digits. An integer that begins with 0 and followed by other digits is assumed to be octal; otherwise, it is assumed to be decimal."

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by LiawiFelix** [comment]
Thank you very much
