### ISSUE TITLE
Live Range 的問題

### ISSUE THREAD

**Issue by hsiao-po-sheng** [compiler-f20/discussion#83]
在 L12 P.13 中 Live Range 為什麼都只有到最後一次使用的前一個指令?
Live Range 的定義不是到最後一次的使用嗎?

**Comment by ypyou** [comment]
As I have mentioned in class, the live range of a value begins when it is written, and ends when that value is last read. Therefore, once the live range of a value (say `A`) ends at the decode pipeline stage, we may allocate the same register that `A` occupies to another value (say `B`), whose live range just starts at this moment, since B is written (at the writeback pipeline stage) after A is read (at the decode pipeline stage, which is before the writeback stage for the register).

**Comment by hsiao-po-sheng** [comment]
所以 A 讀完就馬上洗掉的意思嗎?

**Comment by ypyou** [comment]
Correct

**Comment by hsiao-po-sheng** [comment]
謝謝
